/**
 * Problem 2
 * https://projecteuler.net/problem=2
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 */

const log = require("./helper");

function evenFibonacciNumbers(num) {
    // We need a way to backtrack steps across the numbers 1 and 2 and build up from
    // We will have an array that would contain initial numbers 1 and 2, since the instruction says
    // starting with 1 and 2
    const results = [1, 2]

    // We will build up this array to now contain all the fibonacci sums starting with these numbers, using a loop
    // our "num" in this case will be 4 million and we cannot exceed that value so we will go with i < num
    // We also need to monitor our sum to ensure it does not go beyond the number set
    for (let i = 2; i < num; i++) {
        let nextNumber = i - 2;
        let previousNumber = i - 1;
        let sum = results[nextNumber] + results[previousNumber];
        if (sum <= num) {
            results.push(results[nextNumber] + results[previousNumber]);
        } else {
            break;
        }
    }
    return results.filter(result => result % 2 === 0)
        .reduce((previous, current) => previous + current, 0);
}

log(evenFibonacciNumbers(4000000)); // 4613732